name: she_secure
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  provider: ^6.1.1
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  charts_flutter: ^0.12.0
  fluttertoast: ^8.2.10
  flutter_bluetooth_serial: ^0.4.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
